{% set name = "libxc" %}
{% set version = "6.2.2" %}
{% set sha256 = "ec292de621e819b03a37db1f7a7365a9eaf423e30e2fd4553e6336eca534cc29" %}
{% set cuda_compiler_version = cuda_compiler_version or "None" %}
{% set proc_type = "cuda_" if cuda_compiler_version != "None" else "cpu_" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://gitlab.com/libxc/libxc/-/archive/{{ version }}/libxc-{{ version }}.tar.bz2
  patches:
    - 0001-disable-longest-4th-deriv-offenders-and-rework-deriv.patch
    - 0002-treat-pylibxc-as-independent-project.patch
    - 0003-cmake-cuda.patch
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [not linux64 and cuda_compiler_version != "None"]
  skip: true  # [linux64 and cuda_compiler_version == "10.2"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}        # [cuda_compiler_version == "None"]
    - {{ compiler('cxx') }}      # [cuda_compiler_version != "None"]
    - {{ compiler('cuda') }}     # [cuda_compiler_version != "None"]
    - {{ compiler('fortran') }}  # [unix]
    - cmake >=3.1
    - ninja
    - perl
  run:
    - __cuda  # [cuda_compiler_version != "None"]

outputs:
  - name: libxc-c
    build:
      string: {{ proc_type }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage('libxc-c', max_pin='x') }} {{ proc_type }}*
    requirements:
      build:
        - {{ compiler('c') }}        # [cuda_compiler_version == "None"]
        - {{ compiler('cxx') }}      # [cuda_compiler_version != "None"]
        - {{ compiler('cuda') }}     # [cuda_compiler_version != "None"]
        - cmake
        - ninja
        - perl
    files:
      - bin/xc-info                      # [unix]
      - include/*.h                      # [unix]
      - lib/libxc{{ SHLIB_EXT }}*        # [linux]
      - lib/libxc.*dylib                 # [osx]
      - lib/cmake/Libxc/LibxcConfig*     # [unix]
      - lib/cmake/Libxc/LibxcTargets-C*  # [unix]
      - lib/pkgconfig/libxc.pc           # [unix]
      - Library/include/xc*h             # [win]
      - Library/bin/xc*                  # [win]
      - Library/lib/xc*                  # [win]
      - Library/lib/cmake/Libxc          # [win]
    test:
      commands:
        - ls -l $PREFIX/lib                                     # [unix]
        - ls -l $PREFIX/lib/cmake/Libxc                         # [unix]
        - dir "%PREFIX%\Library"                                # [win]
        - dir "%PREFIX%"\Library\include                        # [win]
        # Verify library
        - test -L $PREFIX/lib/libxc$SHLIB_EXT                   # [unix]
        - test ! -f $PREFIX/lib/libxc.a                         # [unix]
        - if not exist %PREFIX%\\Library\\lib\\xc.lib exit 1    # [win]
        - if not exist %PREFIX%\\Library\\bin\\xc.dll exit 1    # [win]
        - test ! -f $PREFIX/lib/libxcf90$SHLIB_EXT              # [unix]
        - test ! -f $PREFIX/lib/libxcf03$SHLIB_EXT              # [unix]
        # Verify accessories
        - test -e $PREFIX/include/xc.h                          # [unix]
        - if not exist %PREFIX%\\Library\\include\\xc.h exit 1  # [win]
        - test -e $PREFIX/lib/cmake/Libxc/LibxcConfig.cmake     # [unix]
        - test -e $PREFIX/lib/cmake/Libxc/LibxcTargets-C.cmake  # [unix]
        - test ! -f $PREFIX/lib/cmake/Libxc/LibxcTargets-Fortran.cmake  # [unix]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\Libxc\\LibxcConfig.cmake exit 1  # [win]
        - test -e $PREFIX/lib/pkgconfig/libxc.pc                # [unix]
        - test ! -f $PREFIX/lib/pkgconfig/libxcf90.pc           # [unix]
        - test ! -f $PREFIX/lib/pkgconfig/libxcf03.pc           # [unix]
        # Inspect linkage
        - xc-info 100                                           # [unix]
        - xc-info.exe 100                                       # [win]
        - ldd -v $PREFIX/lib/libxc$SHLIB_EXT                    # [linux and build_platform == target_platform]
        - ldd -v $PREFIX/bin/xc-info                            # [linux and build_platform == target_platform]
        - otool -L $PREFIX/lib/libxc$SHLIB_EXT                  # [osx]

  - name: libxc
    build:
      skip: true  # [win]
      string: {{ proc_type }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage('libxc', max_pin='x') }} {{ proc_type }}*
    requirements:
      build:
        - {{ compiler('c') }}        # [cuda_compiler_version == "None"]
        - {{ compiler('cxx') }}      # [cuda_compiler_version != "None"]
        - {{ compiler('cuda') }}     # [cuda_compiler_version != "None"]
        - {{ compiler('fortran') }}            # [unix]
      host:
        - {{ pin_subpackage('libxc-c', exact=True) }}
      run:
        - {{ pin_subpackage('libxc-c', exact=True) }}
    files:
      - include/*.mod                          # [unix]
      - lib/libxcf*{{ SHLIB_EXT }}*            # [unix]
      - lib/cmake/Libxc/LibxcTargets-Fortran*  # [unix]
      - lib/pkgconfig/libxcf*.pc               # [unix]
    test:
      commands:
        # Verify library
        - test -L $PREFIX/lib/libxc$SHLIB_EXT                   # [unix]
        - test ! -f $PREFIX/lib/libxc.a                         # [unix]
        - if not exist %PREFIX%\\Library\\lib\\xc.lib exit 1    # [win]
        - if not exist %PREFIX%\\Library\\bin\\xc.dll exit 1    # [win]
        - test -L $PREFIX/lib/libxcf90$SHLIB_EXT                # [unix]
        - test -L $PREFIX/lib/libxcf03$SHLIB_EXT                # [unix]
        # Verify accessories
        - test -e $PREFIX/include/xc.h                          # [unix]
        - if not exist %PREFIX%\\Library\\include\\xc.h exit 1  # [win]
        - test -e $PREFIX/lib/cmake/Libxc/LibxcConfig.cmake     # [unix]
        - test -e $PREFIX/lib/cmake/Libxc/LibxcTargets-C.cmake  # [unix]
        - test -e $PREFIX/lib/cmake/Libxc/LibxcTargets-Fortran.cmake  # [unix]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\Libxc\\LibxcConfig.cmake exit 1  # [win]
        - test -e $PREFIX/lib/pkgconfig/libxc.pc                # [unix]
        - test -e $PREFIX/lib/pkgconfig/libxcf90.pc             # [unix]
        - test -e $PREFIX/lib/pkgconfig/libxcf03.pc             # [unix]
        # Inspect linkage
        - ldd -v $PREFIX/lib/libxcf03$SHLIB_EXT                 # [linux and build_platform == target_platform]
        - otool -L $PREFIX/lib/libxcf03$SHLIB_EXT               # [osx]

  - name: pylibxc
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    build:
      string: {{ proc_type }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
    requirements:
      build:
        - cmake
        - ninja
        - python                                        # [build_platform != target_platform]
        - cross-python_{{ target_platform }}            # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('libxc-c', exact=True) }}
        - python
      run:
        - {{ pin_subpackage('libxc-c', exact=True) }}
        - python
        - numpy
    test:
      imports:
        - pylibxc
      files:
        - test_pylibxc.py
      commands:
        - ls -l $SP_DIR/pylibxc                                 # [unix]
        - dir %SP_DIR%\pylibxc                                  # [win]
        # Verify module
        - test -f $SP_DIR/pylibxc/__init__.py                   # [unix]
        - if not exist %SP_DIR%\\pylibxc\\__init__.py exit 1    # [win]
        # Actually test
        - python test_pylibxc.py

about:
  home: http://www.tddft.org/programs/Libxc
  dev_url: https://gitlab.com/libxc/libxc
  doc_url: https://www.tddft.org/programs/libxc/manual/
  license: MPL-2.0
  license_url: https://opensource.org/licenses/MPL-2.0
  license_file: COPYING
  license_family: Other
  summary: M.A.L. Marques's exchange-correlation functionals for density-functional theory

extra:
  feedstock-name: libxc
  recipe-maintainers:
    - jan-janssen
    - loriab
